version: "3.9"
services:
  ballot:
    build: ballot
    ports:
      - "30040:8080"
  voter:
    build: voter
    tty: true
    stdin_open: true
    ports: 
      - "30041:80"
    environment:
      REACT_APP_BALLOT_ENDPOINT:  "${HOSTIP}:30040"
      REACT_APP_EC_SERVER_ENDPOINT: "${HOSTIP}:30042"
    links:
      - ballot
      - ecserver
  ecserver:
    build: ecserver
    ports: 
      - "30042:8081"
  election-commission:
    build: election-commission
    tty: true
    stdin_open: true
    ports: 
      - "30043:80"
    environment:
      REACT_APP_EC_SERVER_ENDPOINT: "${HOSTIP}:30042"
    links:
      - ecserver
